# Generated by Django 3.1 on 2020-09-24 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('import_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('import_by', models.CharField(blank=True, max_length=50, null=True)),
                ('export_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('export_by', models.CharField(blank=True, max_length=50, null=True)),
                ('export_to', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt_2.category_2')),
            ],
        ),
    ]
